# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1489069400);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1489069520);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1489069040);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1489069280);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1489069160);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1489069640);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 36);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1489070768284");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1489072545284");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1489068925020");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1489072525020");
user_pref("browser.search.countryCode", "HU");
user_pref("browser.search.region", "HU");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20170221163301");
user_pref("browser.slowStartup.averageTime", 1633);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20170221163301");
user_pref("browser.startup.homepage_override.mstone", "45.7.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":1}");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1487752852988");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1487666514149");
user_pref("datareporting.policy.firstRunTime", "1487666452988");
user_pref("datareporting.sessions.current.activeTicks", 6);
user_pref("datareporting.sessions.current.firstPaint", 1312);
user_pref("datareporting.sessions.current.main", 201);
user_pref("datareporting.sessions.current.sessionRestored", 1965);
user_pref("datareporting.sessions.current.startTime", "1489071601703");
user_pref("datareporting.sessions.current.totalTime", 26);
user_pref("datareporting.sessions.currentIndex", 11);
user_pref("datareporting.sessions.previous.10", "{\"s\":1489068918730,\"a\":189,\"t\":2669,\"c\":true,\"m\":350,\"fp\":2066,\"sr\":2102}");
user_pref("datareporting.sessions.previous.9", "{\"s\":1488709247355,\"a\":35,\"t\":33286,\"c\":true,\"m\":420,\"fp\":1815,\"sr\":2498}");
user_pref("datareporting.sessions.prunedIndex", 8);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 5);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.bootstrappedAddons", "{\"loop@mozilla.org\":{\"version\":\"1.1.14\",\"type\":\"extension\",\"descriptor\":\"/usr/lib64/firefox/browser/features/loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:45.7.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1489069400);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "45.7.0");
user_pref("extensions.lastPlatformVersion", "45.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"loop@mozilla.org\":{\"d\":\"/usr/lib64/firefox/browser/features/loop@mozilla.org.xpi\",\"e\":true,\"v\":\"1.1.14\",\"st\":1487695578000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"45.7.0\",\"st\":1487695577000}}}");
user_pref("gecko.buildID", "20170221163301");
user_pref("gecko.mstone", "45.7.0");
user_pref("idle.lastDailyNotification", 1489068993);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1487666515);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20170221163301");
user_pref("media.gmp-manager.lastCheck", 1489068981);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1488709350);
user_pref("places.history.expiration.transient_current_max_pages", 39234);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1487666643);
user_pref("toolkit.startup.last_success", 1489071601);
user_pref("toolkit.telemetry.cachedClientID", "600c351d-6a88-447e-a579-0a49212b9d4f");
user_pref("toolkit.telemetry.previousBuildID", "20170221163301");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
